# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updata', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
