# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-22 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190122_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
